// Mongoose Module Import
const { name } = require("ejs");
const mongoose = require("mongoose");

// Database Connection - EDIT THIS TO CLOUD FOR LATER TESTING
const connect = mongoose.connect("mongodb://localhost:27017/readifyTesting")

// Database Connection Test
connect.then(() => {
    console.log("Database Connection Successful.");
})
.catch(() => {
    console.log("Database Connection Failed.")
})

// Schema Creation - Edit Here when creating new variables for the database

// Schema for New Users
const loginSchema = new mongoose.Schema({
    name: {
        type: String,
        required: true
    },
    password: {
        type: String,
        required: true
    },
    email: {
        type: String,
        required: true
    },
    isAdmin: {
        type: Boolean,
        required: true,
        default: false
    },
});

// Schema for Tests
const questionSchema = new mongoose.Schema({
    questionNumber: { 
        type: Number, 
        required: true 
    },
    questionText: { 
        type: String, 
        required: true 
    },
    data: { 
        type: mongoose.Schema.Types.Mixed 
    }, 
    correctAnswer: { 
        type: mongoose.Schema.Types.Mixed, 
        required: true 
    }
}, { _id: false }) // Stops Object ID Generation

const passageSchema = new mongoose.Schema({
    testId: {                           // Autogenerated
        type: Number, 
        unique: true 
    },
    testDesignation:{                   // Checkbox or Dropdown
        type: Boolean,
        required: true,
    },
    testType: {                         // Dropdown
        type: Number, 
        required: true,
        enum: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11] 
    },
    passageTitle: {                     // Textbox
        type: String, 
        required: true },
    passage: {                          // Textbox
        type: String, 
        required: true },
    questions: {                        // Textbox
        type: [questionSchema], 
        default: [] },
});

// Database Collection
const readifyCollection = new mongoose.model("users", loginSchema);
const questionCollection = new mongoose.model("questions",questionSchema);
const passageCollection = new mongoose.model("passages", passageSchema);

// Exporting Model
module.exports = {readifyCollection, questionCollection, passageCollection};

