// Mongoose Module Import
const { name } = require("ejs");
const mongoose = require("mongoose");

// Database Connection - EDIT THIS TO CLOUD FOR LATER TESTING
const connect = mongoose.connect("mongodb://localhost:27017/readifyTesting")

// Database Connection Test
connect.then(() => {
    console.log("Database Connection Successful.");
})
.catch(() => {
    console.log("Database Connection Failed.")
})

// Schema Creation - Edit Here when creating new variables for the database

// Schema for New Users
const loginSchema = new mongoose.Schema({
    name: {
        type: String,
        required: true
    },
    password: {
        type: String,
        required: true
    },
    email: {
        type: String,
        required: true
    },
    isAdmin: {
        type: Boolean,
        required: true,
        default: false
    },
});

//  Example Test
// {
//   "_id": { "$oid": "65566f140026e959c90a1f73" },
//   "testId": 103,
//   "passageTitle": "The Antarctic Ice Shelf",
//   "passage": "...",
//   "testType": 2, // <--- This means ALL questions are True False Not Given
//   "questions": [
//     {
//       "questionNumber": 1,
//       "questionText": "Ice shelves are permanently attached to land.",
//       "correctAnswer": "True"
//     },
//     {
//       "questionNumber": 2,
//       "questionText": "The shelf was discovered in 1841.",
//       "correctAnswer": "Not Given"
//     }
//   ]
// }

// Schema for Tests
const QuestionSchema = new mongoose.Schema({
    questionNumber: { 
        type: Number, 
        required: true 
    },
    questionText: { 
        type: String, 
        required: true 
    },
    data: { 
        type: mongoose.Schema.Types.Mixed 
    }, 
    correctAnswer: { 
        type: mongoose.Schema.Types.Mixed, 
        required: true 
    }
}, { _id: false }) // Stops Object ID Generation

const passageSchema = new mongoose.Schema({
    testId: {                           // Autogenerated
        type: Number, 
        required: true, 
        unique: true 
    },
    testDesignation:{                   // Checkbox or Dropdown
        type: Boolean,
        required: true,
    },
    testType: {                         // Dropdown
        type: Number, 
        required: true,
        enum: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11] 
    },
    passageTitle: {                     // Textbox
        type: String, 
        required: true },
    passage: {                          // Textbox
        type: String, 
        required: true },
    questions: {                        // Textbox
        type: [QuestionSchema], 
        default: [] },
});

// Database Collection
const readifyCollection = new mongoose.model("users", loginSchema);
const passageCollection = new mongoose.model("passages", passageSchema);

// Exporting Model
module.exports = readifyCollection;

